### ISSUE TITLE
don't JSON.stringify log objects

### ISSUE THREAD

**Issue by davidmarkclements** [apparatus/mu#24]
I'm seeing this a lot: 

```js
    mu.log.debug('node: ' + muid + ' <- ' + JSON.stringify(msg))
```

That's going to JSON.stringify every time, even if the logging level is above debug 

Instead let pino deal with it

```js
    mu.log.debug('node: %s <- %j', muid, msg)
```

This way the object will only be (safely) stringified if logging is on

**Comment by mcollina** [comment]
This is already fixed in https://github.com/apparatus/mu/pull/21

**Comment by davidmarkclements** [comment]
ah sorry, thought that was already merged when I wrote this - good for posterity though
