### ISSUE TITLE
modularise moar - convert to monorepo

### ISSUE THREAD

**Issue by davidmarkclements** [apparatus/mu#26]
this module should be core

drivers and adapters should have their own modules

**Comment by davidmarkclements** [comment]
I'd like to try the monorepo approach with lerna (http://lernajs.io) 

This would mean changing the folder structure to 

```
packages/
  ├── mu/
  ├── mu-tcp/
  ├── mu-func/
  ├── mu-tee/
  ├── mu-balancer/
```

Each package would be published as it's own independent module

The advantage is we can modularise the internals but keep "core functionality" in the same place.

The alternative is to have multiple repos (the usual) 

cc @pelger @mcollina

**Comment by mcollina** [comment]
I'm all in for lerna. If it works for pouchdb or babel, it might works for us too!

**Comment by davidmarkclements** [comment]
The pieces that should be modules are integral to core, so it makes sense in our case
