### ISSUE TITLE
what's msg.pattern.__err about and is there a better way?

### ISSUE THREAD

**Issue by davidmarkclements** [apparatus/mu#27]
It's possible that we do need some way of injecting errors into patterns (although I'd like to validate that thought, to be sure)
but shouldn't errors be on a meta data object (as agreed), rather than going down the "super private" double underscore route?

**Comment by davidmarkclements** [comment]
so it seems to be a way to force an error event with patterns - however it's only currently supported in the function driver

I'm guessing it's a way to propagate errors across services? 

I'd like to standardise this with [`mu-error`](http://npm.im/mu-error) in some way

cc @mcollina @pelger

**Comment by mcollina** [comment]
I'm missing some context. Why and where are we attaching errors to patterns?
Errors always come first on the callback. We wiil need a way to return that to the user.

**Comment by davidmarkclements** [comment]
see https://github.com/apparatus/mu/blob/master/drivers/function-driver/driver.js#L54-L56

and then https://github.com/apparatus/mu/blob/master/test/drivers/force-driver-error.test.js

I'm guessing that @pelger initial reason was to propagate errors across services, now that we have distributed error handling with `mu-error` I think it should be safe to remove

**Comment by mcollina** [comment]
Agreed.
