### ISSUE TITLE
side loading core instance into transports (setMu)

### ISSUE THREAD

**Issue by davidmarkclements** [apparatus/mu#29]
and generally calling functions on objects that hoist values to scoped variables

I think to be more functional, we should be taking a more vertical state approach 
by which I mean passing all state into a function which calls another functions, and so on

cc @pelger @mcollina @lucamaraschi @mcdonnelldean

**Comment by mcollina** [comment]
I'm definitely 👍 for this, and completely avoid `setMu`.
