### ISSUE TITLE
rename func to local

### ISSUE THREAD

**Issue by davidmarkclements** [apparatus/mu#49]
soon we'll be going to monorepo - transports will be published to npm, so mu/drivers/tcp will be `mu-tcp`,   mu/drivers/http would be `mu-http`    

`mu-func` sounds like ambigious `mu-local` is clearer

(for these main cases, I would advocate not adding `-driver` or `-transport` to the end of each)

@mcollina @pelger

**Comment by mcollina** [comment]
+1 for mu-local.
