### ISSUE TITLE
mu v seneca transport

### ISSUE THREAD

**Issue by tomdavidson** [apparatus/mu#70]
Im new to the scene and trying to understand. Can someone compare and contrast mv and senecajs transport?

**Comment by pelger** [comment]
Hey @tomdavidson, they are very similar in intent. The aim of Mu is to implement two of the key ideas in seneca namely - 1). pattern matching / pattern language and 2). transport independence. The idea is to provide a simple lightweight module that doesn't have the rest of the overhead that comes with the seneca framework. In short if you want to use a full framework then go with seneca, if you prefer something that is more cut down then go with Mu - hope that helps?

**Comment by tomdavidson** [comment]
Perfect explanation and just want I needed. Thank you.

**Comment by pelger** [comment]
Welcome :)

**Comment by tomdavidson** [comment]
Adding on to this closed issue for other inquirers. At this time Mu does not have its own distributed messaging such as Seneca Mesh.
