### ISSUE TITLE
example using mu-redis?

### ISSUE THREAD

**Issue by tomdavidson** [apparatus/mu#73]
Hello anyone have a project using mu-redis that I can check out?

**Comment by davidmarkclements** [comment]
Hi @tomdavidson this is all very early work atm, if you're planning on using mu-redis on a project you may be the first - you can ping @pelger and I on twitter if you need help etc.

**Comment by tomdavidson** [comment]
Thanks for the perspective @davidmarkclements . Perhaps for this round we should go ahead and bite off on Seneca.
